### ISSUE TITLE
Warning when there's a : in a filename

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/gettext#184]
I just noticed `:` in filenames break gettext. I'm not sure if that can be supported, but at least gettext should issue a warning if it sees such a file.

**Comment by josevalim** [comment]
@LostKobrakai thanks. In the filename of what though? .po? .pot? What is your gettext version?

**Comment by josevalim** [comment]
Also, which error are you getting? can you post the full message with stacktrace?

**Comment by LostKobrakai** [comment]
It was the filename of the file holding the translation.

Error was: 
```
** (FunctionClauseError) no function clause matching in anonymous fn/2 in Gettext.PO.dump_references/1
    lib/gettext/po.ex:280: anonymous fn({3}, 90) in Gettext.PO.dump_references/1
    (elixir) lib/enum.ex:1068: anonymous fn/3 in Enum.flat_map_reduce/3
    (elixir) lib/enum.ex:3281: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1067: Enum.flat_map_reduce/3
    lib/gettext/po.ex:280: Gettext.PO.dump_references/1
    lib/gettext/po.ex:237: Gettext.PO.dump_translation/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
Function: &:erlang.apply/2
    Args: [#Function<2.80905071/1 in Mix.Tasks.Gettext.Merge.merge_dirs/5>, ["priv/gettext/default.pot"]]
```
when doing `mix gettext.merge …`

**Comment by LostKobrakai** [comment]
Version is 0.15.0
