### ISSUE TITLE
Cannot read multiple #: references on one line

### ISSUE THREAD

**Issue by tmjoen** [elixir-lang/gettext#46]
When I use Poedit it saves the .po file like this:

```
#: web/views/dashboard_view.ex:5 web/views/dashboard_view.ex:10
#: web/views/dashboard_view.ex:20
msgid "Memory"
msgstr "Minne"
```

with multiple source code references on same line (there is a wrap-at preference setting in poedit).

This makes gettext choke:

````
== Compilation error on file lib/brando/gettext.ex ==
** (MatchError) no match of right hand side value: ["web/views/dashboard_view.ex", "5 web/views/dashboard_view.ex", "10"]
    lib/gettext/po/parser.ex:53: Gettext.PO.Parser.parse_reference/1
    lib/gettext/po/parser.ex:47: anonymous fn/2 in Gettext.PO.Parser.extract_references/1
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/gettext/po/parser.ex:45: Gettext.PO.Parser.extract_references/1
    lib/gettext/po/parser.ex:34: Gettext.PO.Parser.to_struct/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
```

This looks to be a valid way to print references, at least according to the GNU gettext manual:

```
#: src/msgcmp.c:338 src/po-lex.c:699
#, c-format
msgid "found %d fatal error"
msgid_plural "found %d fatal errors"
msgstr[0] "s'ha trobat %d error fatal"
msgstr[1] "s'han trobat %d errors fatals"
```

**Comment by whatyouhide** [comment]
@tmjoen whoops, gonna fix that as soon as possible and release 0.6.2. :)
